## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.test("SMC"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("SMC")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
