## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
git:
  depth: 99999999

script:
  - julia -e 'Pkg.clone(pwd()); Pkg.test("SMC"; coverage=true)'
#  - julia -e 'Pkg.clone("https://github.com/tlienart/ExpFamily.jl.git"); using ExpFamily; Pkg.clone(pwd()); Pkg.test("SMC"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("SMC")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
